I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 356, in script
    with dissolve (1.0)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 356, in script
    with dissolve (1.0)
  File "C:\Users\Logan Weber\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1658, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\Logan Weber\Downloads\renpy-8.0.3-sdk\renpy\exports.py", line 1657, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Logan Weber\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 2798, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\Logan Weber\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\Logan Weber\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 3752, in interact_core
    trans = self.ongoing_transition[None](
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Astromorbus 1.0
Sun Feb 12 05:56:36 2023
